# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptions',
            new_name='description',
        ),
    ]
