# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_place_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='serves_pizzs',
            new_name='serves_pizza',
        ),
    ]
